### ISSUE TITLE
Layer Key LT(layer,key,hold_duration) Not working as intended.

### ISSUE THREAD

**Issue by jash-maester** [andrew-hardin/virtual-space-cadet#1]
Upon Testing Virtual Space Cadet on Manjaro Running Linux kernel 5.9.11, noticed a bug on the example scripts. I was using the Vim-Cursor example keyboard layout and found even after releasing the SPACEBAR (KC_SPACE) the layout didn't returned to normal. Am I missing something here? Again I am using the default config present in the examples nothing changed. I am doing this on ASUS ROG GL553 VE Laptop. 

Thank Again for this wonderful creation. But Switching between layers seems to be not working for me. I don't know Rust yet. Hoping to contribute to the project in future. Awaiting Your Reply.

**Comment by jash-maester** [comment]
On A second NOTE: None of the other Layer Keys TG(layer), MO(layer), AL(layer) and OSL(layer) works, except LT()
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Failed to convert key tree into a key."', /home/jash_maester/.cargo/git/checkouts/virtual-space-cadet-cc1d2da8febc7cfd/b15950f/libspacecadet/src/keyboard_driver.rs:170:84
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

Rust Giving error.

After Backtracing:

```sh
$ sudo RUST_BACKTRACE=full spacecadet --device /dev/input/event18 --layer layers.json --matrix matrix.json
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Failed to convert key tree into a key."', /home/jash_maester/.cargo/git/checkouts/virtual-space-cadet-cc1d2da8febc7cfd/b15950f/libspacecadet/src/keyboard_driver.rs:170:84
stack backtrace:
   0:     0x55a3cc136830 - std::backtrace_rs::backtrace::libunwind::trace::h3244117ea50123fe
                               at /build/rust/src/rustc-1.48.0-src/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:     0x55a3cc136830 - std::backtrace_rs::backtrace::trace_unsynchronized::h68c610493487144f
                               at /build/rust/src/rustc-1.48.0-src/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:     0x55a3cc136830 - std::sys_common::backtrace::_print_fmt::h98a015f47bac7d62
                               at /build/rust/src/rustc-1.48.0-src/library/std/src/sys_common/backtrace.rs:79
   3:     0x55a3cc136830 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc852ad3e88e43049
                               at /build/rust/src/rustc-1.48.0-src/library/std/src/sys_common/backtrace.rs:58
   4:     0x55a3cc150e2c - core::fmt::write::h5437b03347b2ec7a
                               at /build/rust/src/rustc-1.48.0-src/library/core/src/fmt/mod.rs:1080
   5:     0x55a3cc133be5 - std::io::Write::write_fmt::h1c132b3b8a60ce2f
                               at /build/rust/src/rustc-1.48.0-src/library/std/src/io/mod.rs:1516
   6:     0x55a3cc1389ad - std::sys_common::backtrace::_print::hdfae0c73b5d1550a
                               at /build/rust/src/rustc-1.48.0-src/library/std/src/sys_common/backtrace.rs:61
   7:     0x55a3cc1389ad - std::sys_common::backtrace::print::h846d8b35d353226f
                               at /build/rust/src/rustc-1.48.0-src/library/std/src/sys_common/backtrace.rs:48
   8:     0x55a3cc1389ad - std::panicking::default_hook::{{closure}}::h611a677a9567debb
                               at /build/rust/src/rustc-1.48.0-src/library/std/src/panicking.rs:208
   9:     0x55a3cc138658 - std::panicking::default_hook::hfc5e7967f3ac8efb
                               at /build/rust/src/rustc-1.48.0-src/library/std/src/panicking.rs:227
  10:     0x55a3cc139091 - std::panicking::rust_panic_with_hook::h86da1db1d0779194
                               at /build/rust/src/rustc-1.48.0-src/library/std/src/panicking.rs:577
  11:     0x55a3cc138c39 - std::panicking::begin_panic_handler::{{closure}}::h8deb4831e8e5befc
                               at /build/rust/src/rustc-1.48.0-src/library/std/src/panicking.rs:484
  12:     0x55a3cc136c9c - std::sys_common::backtrace::__rust_end_short_backtrace::h67eb25f573b71150
                               at /build/rust/src/rustc-1.48.0-src/library/std/src/sys_common/backtrace.rs:153
  13:     0x55a3cc138bf9 - rust_begin_unwind
                               at /build/rust/src/rustc-1.48.0-src/library/std/src/panicking.rs:483
  14:     0x55a3cc150141 - core::panicking::panic_fmt::h8d2c19297fe96b44
                               at /build/rust/src/rustc-1.48.0-src/library/core/src/panicking.rs:85
  15:     0x55a3cc14ff63 - core::option::expect_none_failed::h1a6f64ce49780e5b
                               at /build/rust/src/rustc-1.48.0-src/library/core/src/option.rs:1234
  16:     0x55a3cc099fef - libspacecadet::keyboard_driver::KeyboardDriver<I,O>::load_layers::h402f770fef8390f1
  17:     0x55a3cc09f43e - spacecadet::main::hc50caa76fd1b517b
  18:     0x55a3cc097e83 - std::sys_common::backtrace::__rust_begin_short_backtrace::h1a48b0e18835134b
  19:     0x55a3cc097e99 - std::rt::lang_start::{{closure}}::hdf5671745de11bc3
  20:     0x55a3cc1394b7 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hba2eeded6e43561f
                               at /build/rust/src/rustc-1.48.0-src/library/core/src/ops/function.rs:259
  21:     0x55a3cc1394b7 - std::panicking::try::do_call::h2d2f9a7ece5d85e2
                               at /build/rust/src/rustc-1.48.0-src/library/std/src/panicking.rs:381
  22:     0x55a3cc1394b7 - std::panicking::try::he67fa7d0004e7010
                               at /build/rust/src/rustc-1.48.0-src/library/std/src/panicking.rs:345
  23:     0x55a3cc1394b7 - std::panic::catch_unwind::h61fcdf94f063131b
                               at /build/rust/src/rustc-1.48.0-src/library/std/src/panic.rs:382
  24:     0x55a3cc1394b7 - std::rt::lang_start_internal::h0c3b9dc1678c8c77
                               at /build/rust/src/rustc-1.48.0-src/library/std/src/rt.rs:51
  25:     0x55a3cc09f7f2 - main
  26:     0x7fab196d0152 - __libc_start_main
  27:     0x55a3cc09708e - _start
  28:                0x0 - <unknown>

```
